#!/usr/bin/env bash

set -e

program="${0##*/}"

print_usage() {
    echo "${program} MPEGTS"
}

[[ ${#} != 1 ]] && print_usage >&2 && exit 1

ffprobe "${1}" 2>&1 | rg -qF 'Stream #0:0: Video: png, rgba(pc)'

get_size(){
  stat -c %s "${1}"
}

file="${1}"
file_without_extension="${file%.*}"
size=$(get_size "${file}")

mv "${file}" "${file_without_extension}"

ffmpeg -y -f mpegts -i "${file_without_extension}" -c copy "${file}"

ratio_gt_1=$(echo "(${size} / $(get_size "${file}")) > 1" | bc -l)

[[ ${ratio_gt_1} == 1 ]] && rm -v "${file_without_extension}"
